# Generated by Django 4.2.1 on 2023-05-08 04:34

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
